import type { Metadata } from "next";
import { ComponentProps } from "@/types";
import { AuthProvider } from "@/providers/AuthProvider";
import { AuthGuard } from "@/components/backend/Guards/AuthGuard";
import { CustomizerProvider } from "@/providers/CustomizerProvider";
import { LayoutProvider } from "@/providers/LayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "/assets/images/favicon.png",
      rel: "icon",
      type: "image/x-icon",
    },
    {
      url: "/assets/images/favicon.png",
      rel: "shortcut icon",
      type: "image/x-icon",
    },
  ],
};

export default async function BackendLayout({ children }: ComponentProps) {
  return (
    <>
      <AuthProvider>
        <CustomizerProvider>
          <LayoutProvider>
            <AuthGuard>{children}</AuthGuard>
          </LayoutProvider>
        </CustomizerProvider>
      </AuthProvider>
    </>
  );
}
