import type { Metadata } from "next";
import { ComponentProps } from "@/types";
import { AuthProvider } from "@/providers/AuthProvider";
import { Suspense } from "react";
import { Spinner } from "@/components/Spinner";
import NextAuthProvider from "@/providers/NextAuthProvider";
import AuthGuard from "@/components/Guards/AuthGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function BackendLayout({ children }: ComponentProps) {
  return (
    <NextAuthProvider>
      <AuthProvider>
        <Suspense fallback={<Spinner />}>
          <AuthGuard>{children}</AuthGuard>
        </Suspense>
      </AuthProvider>
    </NextAuthProvider>
  );
}
