import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { locales } from "@/configs/i18n";
import { notFound } from "next/navigation";
import { unstable_setRequestLocale } from "next-intl/server";
import { ComponentProps } from "@/types";
import { APP_LANGUAGE } from "@/environment";
import { ApolloProvider } from "@/providers/ApolloProvider";
import { Suspense } from "react";
import { Spinner } from "@/layouts/backend/Spinner";
import { ToastContainer } from "react-toastify";
import { ReduxProvider } from "@/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: ComponentProps) {
  const locale = params?.locale ?? APP_LANGUAGE;
  unstable_setRequestLocale(locale);

  let messages;
  try {
    messages = (await import(`../../locales/${locale}.json`)).default;
  } catch (error) {
    console.error(error);

    return notFound();
  }

  if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ApolloProvider>
            <ReduxProvider>
              <Suspense fallback={<Spinner />}>{children}</Suspense>
            </ReduxProvider>
          </ApolloProvider>
        </NextIntlClientProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
