name: CI - Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '20'
          check-latest: true

      - name: Install Npm Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Run tests with jest
        run: npm run test
